[package]
name = "kr_maps"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
multiinput = "0.1.0"
ron = "0.7"
serde = { version = "1", features = ["derive"] }
autopilot = "0.4.0"
